# Generated by Django 3.0.8 on 2020-08-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0004_ordermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='status',
        ),
    ]
